spring:
   profiles:
      active: prod
   jpa:
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5InnoDBDialect
            ddl-auto: validate
            format_sql: true
      show-sql: true
      generate-ddl: true
   flyway:
      baseline-on-migrate: true
      enable: true
      baseline-description: init
      baseline-version: 0