# Server
server:
   port: 8080

# Variables
user:
   admin:
      email: ${USER_ADMIN_EMAIL}
      password: ${USER_ADMIN_PASSWORD}
      name: GasOut ADMIN
mqtt:
   client:
      url: ${MQTT_CLIENT_URL}
      id: ${MQTT_CLIENT_ID}
aws:
   client:
      access-key:
         id: ${AWS_CLIENT_ACCESS_KEY_ID}
         secret: ${AWS_CLIENT_ACCESS_KEY_SECRET}
firebase:
   api-key: ${FIREBASE_API_KEY}

# Spring config
spring:
   main:
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   application:
      name: gas-out-api-prod
   datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

# Swagger-ui Custom Path
springdoc:
   swagger-ui:
      path: /swagger-ui.html