logging:
   level:
      ROOT: INFO

server:
   port: 8089

user:
   admin:
      email: contato.gasout@gmail.com
      password: 
      name: GasOut ADMIN

spring:
   application:
      name: gas-out-api-local
   main:
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: contato.gasout@gmail.com
      password:
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   datasource:
      url: jdbc:mysql://localhost:3306/gasoutdev?createDatabaseIfNotExist=true
      username: root
      password:
   flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: audit
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

springdoc:
   swagger-ui:
      path: /swagger-ui.html