logging:
   level:
      ROOT: INFO

server:
   port: 8089

user:
   admin:
      email: ${USER_EMAIL:contato.gasout@gmail.com}
      password: ${USER_PASSWORD:GasOut@2022!}
      name: GasOut ADMIN

spring:
   application:
      name: gas-out-api-local
   main:
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME:contato.gasout@gmail.com}
      password: ${SPRING_MAIL_PASSWORD:vjtvrwgangxbawwm}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   datasource:
      url: jdbc:mysql://localhost:3306/gasoutdev?createDatabaseIfNotExist=true
      username: ${SPRING_DATASOURCE_USER:root}
      password: ${SPRING_DATASOURCE_PASSWORD:root}
   flyway:
      url: jdbc:mysql://localhost:3306/
      schemas: audit
      user: ${spring.datasource.username}
      password: ${spring.datasource.password}

springdoc:
   swagger-ui:
      path: /swagger-ui.html