logging:
   level:
      ROOT: INFO

server:
   port: 8080

user:
   admin:
      email: ${USER_ADMIN_EMAIL}
      password: ${USER_ADMIN_PASSWORD}
      name: GasOut ADMIN
aws:
   client:
      access-key:
         id: ${AWS_CLIENT_ACCESS_KEY_ID}
         secret: ${AWS_CLIENT_ACCESS_KEY_SECRET}
firebase:
   api-key: ${FIREBASE_API_KEY}
api:
   security:
      token:
         secret: ${JWT_SECRET}

spring:
   application:
      name: gas-out-api-prod
   main:
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
   flyway:
      url: ${SPRING_DATASOURCE_URL}
      schemas: audit
      user: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
   swagger-ui:
      path: /swagger-ui.html