# Server
server:
   port: 8080

# Variables
user:
   admin:
      email: ${USER_ADMIN_EMAIL}
      password: ${USER_ADMIN_PASSWORD}
      name: GasOut ADMIN

# Spring config
spring:
   main:
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   application:
      name: gas-out-api-prod
   datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
   swagger-ui:
      path: /swagger-ui.html