server:
   port: 8080

# Variables
user:
   admin:
      email: ${USER_ADMIN_EMAIL}
      password: ${USER_ADMIN_PASSWORD}
      name: GasOut ADMIN

spring:
   main:
# Spring config
      allow-circular-references: true
   mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      properties:
         mail:
            smtp:
               auth: true
               starttls:
                  enable: true
   application:
      name: gas-out-api-prod
   datasource:
      url: jdbc:mysql://${SPRING_DATASOURCE_URL}?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}

springdoc:
   swagger-ui:
      path: /swagger-ui.html
# ------------------
# ------------------
# Orphaned comments:
# ------------------
# Was at begin of line:37 :# Orphaned comments:
# Was at begin of line:38 :# ------------------
# Was at begin of line:39 :# Was at begin of line:33 :# Swagger-ui Custom Path