server:
  port: 8080
  
# Spring config
spring:
  main:
    allow-circular-references: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  application:
    name: gas-out-api-prod
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
      
# Swagger-ui Custom Path
springdoc:
  swagger-ui:
    path: /swagger-ui.html